# Generated by Django 2.0.2 on 2020-03-08 13:46

import api.base.fields
import datetime
from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('active', api.base.fields.StatusField(default=True, verbose_name='active')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='name')),
                ('dob', models.DateField(default=datetime.date.today, verbose_name='date of birth')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
