# Generated by Django 2.0.2 on 2020-03-08 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animal', '0002_animal_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='type',
            field=models.IntegerField(blank=True, choices=[(1, 'Cat'), (2, 'Dog')], null=True, verbose_name='type'),
        ),
    ]
